services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
      POSTGRES_DB: bookdb
    ports:
      - "5435:5432"   # shift away from 5433 since multiple stacks run
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookuser"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://bookuser:bookpass@db:5432/bookdb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "18000:8000"   # instead of 8000, pick a high port

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "18173:80"     # instead of 5173, pick another high port
    depends_on:
      - backend
